# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# Currently only builds on Linux

on:
  push:
    branches: [master, staging, trying]
  pull_request:

name: CI

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install libusb, libudev, and libftdi (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libftdi1-dev libudev-dev
        # Only install on Ubuntu
        if: (matrix.os == 'ubuntu-latest') || (matrix.os == 'ubuntu-20.04')

      - name: Install libftdi (windows)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgArguments: "libftdi1:x64-windows"
          vcpkgGitCommitId: "7dbc05515b44bf54d2a42b4da9d1e1f910868b86"
          vcpkgTriplet: x64-windows

        if: matrix.os == 'windows-latest'

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: check

  test:
    name: Test Suite

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install libusb, libudev, and libftdi (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libftdi1-dev libudev-dev

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install libusb, libudev, and libftdi (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libftdi1-dev libudev-dev

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true

      - name: Install clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
